"""empty message

Revision ID: 64e0cf1b67f2
Revises: b070b725f99a
Create Date: 2020-03-09 00:04:46.489183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e0cf1b67f2'
down_revision = 'b070b725f99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_joined', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_joined')
    # ### end Alembic commands ###
